### ISSUE TITLE
days of the week are incorrect

### ISSUE THREAD

**Issue by jamgian** [tuoxie007/HSUDatePicker#1]
Hi Jason!
I was working with your date picker and i noticed that the weekdays are incorrect. You can see it in your screenshot too as they are "MON THU THU SUN TUE FRI SUN". How can i fix that? thanks

**Comment by tuoxie007** [comment]
fixed, thanks!

**Comment by jamgian** [comment]
Hi Jason!
Thanks for your reply. I'm sorry to say it, but the calendar is missing thursday now

**Comment by tuoxie007** [comment]
Hi jamgian
It should be very correct this time.
Thanks.
- Jason Hsu
