### ISSUE TITLE
last date in month showing up in wrong month.

### ISSUE THREAD

**Issue by ghost** [tuoxie007/HSUDatePicker#2]
Hello,

I downloaded HSUDatePicker yesterday (on more then one mac) and can someone verify this issue?

On my macs running the iOS simulator and on an iPhone 5. Simply downloading the picker and running or installing them results in the last day of Oct. (31) being displayed in Nov. this then offsets the rest of the days in Nov.

So on a brand new download, the days seem to be off by a single day so that the last day of the month is moved and becomes the "first" day of the next month, offsetting all those days in that month.

Enclosed is an image that shows the issue. You will see in the screenshot the incorrect results.

HSUDatePicker thinks today is Sunday Nov 2nd.

Today is really Sunday Nov. 3rd. 2013. 

Also, if you click on Oct. 31. You will see Oct 30 display a black circle as a highlight before it closes the view. So what it thinks is a date when tapping and what it is displaying seems to be different as well.

My macs are running 10.9 mavericks.
I checked the simulator and they are running 7.0.3.
My time zone is Pacific Standard Time.
My iPhone 5 is running 7.0.3
My calendars or Gregorian. (normal USA calendar)
![wrong days](https://f.cloud.github.com/assets/1256322/1461649/6dedf5b0-44c0-11e3-86f6-e56a01797ba2.png)

My times are being set by the apple time clocks.
We did switch Daylight saving time last night but this but was occurring before and after our switch.

Is anyone else seeing this?

thank you.

**Comment by ghost** [comment]
Possible fix. Have not looked into the ramifications of other parts of the code though.

In this method:
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
  {

commenting out this line:

//[calendar setTimeZone:[NSTimeZone timeZoneForSecondsFromGMT:0]];

fixes this issues and the other issue I posted today.

**Comment by tuoxie007** [comment]
thanks, fixed.
