### ISSUE TITLE
weekends "day" not drawing correctly

### ISSUE THREAD

**Issue by ghost** [tuoxie007/HSUDatePicker#3]
Hello.

With the same specs as my prev issue, I noticed that the weekend days are not being drawn in gray correctly.

In the included screenshot you will notice that Sunday does draw the day in a gray color, instead of Sat. being drawn the same way, Monday is drawn in gray.

It should be Sat.

![wrong days](https://f.cloud.github.com/assets/1256322/1461714/f565a66e-44c5-11e3-990f-e7cd8d698431.png)

The "header" days are being correctly drawn in gray. This only affects the actual date cell.

**Comment by ghost** [comment]
Possible fix. Have not looked into the ramifications of other parts of the code though.

In this method:
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
  {

commenting out this line:

//[calendar setTimeZone:[NSTimeZone timeZoneForSecondsFromGMT:0]];

fixes this issues and the other issue I posted today.

**Comment by tuoxie007** [comment]
thanks, fixed.
